import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MET NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.main - 1}>
          Discover A New Era Of Cryptocurrency
        </h1>

        <p className={styles.description}>
          met nft the primier marketplace for NFT, which are digital items you
          can truly own. Digital items have existed for a long time, but never
          like this. eg: movies,musics,scripts etc..
        </p>

        <button className={styles.btn1}>Get Started</button>

        {/*  <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
        <div className="blog">
          <h2>Popular Courses</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>

          <div className="blog">
            <div className="blogItem">
              <Link href="/blogposts/learn-javascript">
                <h3>How to learn JavaScript in 2022</h3>
              </Link>
              <p>JavaScript is the language used to design logic for the web</p>
            </div>
          </div>
          <div className="blog">
            <div className="blogItem">
              <h3>How to learn JavaScript in 2022</h3>
              <p>JavaScript is the language used to design logic for the web</p>
            </div>
          </div>
          <div className="blog">
            <div className="blogItem">
              <h3>How to learn JavaScript in 2022</h3>
              <p>JavaScript is the language used to design logic for the web</p>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
